### ISSUE TITLE
How to use?

### ISSUE THREAD

**Issue by mayank1513** [upgradeQ/OBS-Studio-Cursor-skin#1]
Hi,

please specify python version requirements if any. I have installed latest python today and also did pip install mouse. I don't see any source / settings to use this script.

Please help how to use it in obs

**Comment by mayank1513** [comment]
> 
> 
> Hi,
> 
> please specify python version requirements if any. I have installed latest python today and also did pip install mouse. I don't see any source / settings to use this script.
> 
> Please help how to use it in obs

Solved -- need to use python 3.6

**Comment by Karmalakas** [comment]
I still can't figure out how to select the source in script. I have Python 3.8, but script has no description and no properties :/ 
![image](https://user-images.githubusercontent.com/3602819/101693260-08068c00-3a7a-11eb-8db5-57593f106816.png)

Have path to Python defined in other tab

**Comment by upgradeQ** [comment]
@Karmalakas install 3.6 version from here https://www.python.org/downloads/release/python-368/

**Comment by Karmalakas** [comment]
Ah, I thought it's 3.6 and above :)
It's working now, but there's still issue #2 
Thank you :)
