### ISSUE TITLE
Custom cursor

### ISSUE THREAD

**Issue by Preposi** [upgradeQ/OBS-Studio-Cursor-skin#10]
cursor_shader.lua is working nicely, but I want to change from the default one to my cursor of choice. Is that possible? I asked an AI to assist me, but all of them didn't work. Just to clarify, I tried to change into a static image, which is .png extension.

**Comment by upgradeQ** [comment]
It is possible to  load your .png file [as a texture](https://github.com/obsproject/obs-studio/wiki/Scripting-Tutorial-Halftone-Filter#:~:text=that%20the%20function-,gs_image_file_init_texture,-is%20separated%20from) and use it inside a shader. That is a first step, then you need to rewrite parts of cursor_shader.lua to offset that texture in a source being filtered, this is done in  the HLSL section. 

@Preposi, have you tried using python version of the script? It is supports any source as a cursor.

**Comment by Preposi** [comment]
Thank you, it's working. But I have a new minor issue. Is it possible to display cursor on second monitor instead of main monitor? This is not necessary by any means. Another thing, is there any reason why you cap refresh rate at 15ms? I try 1ms and it's working great.

**Comment by upgradeQ** [comment]
Multi-monitor workflow not yet implemented, 15 ms is for minor optimisation as you will normally record or stream at max 60 FPS. Even if you set 1ms in the code, it will not change timer resolution to 1ms since it is based on the framerate setting.

**Comment by Preposi** [comment]
I changed to 1ms and cursor looked more smooth than 15ms quite a lot. Is it because I record a video in 144FPS?

**Comment by upgradeQ** [comment]
Yes, so for 144 FPS the cap will be ~6ms
