### ISSUE TITLE
Very "easy" and "working" installation

### ISSUE THREAD

**Issue by AngelTs** [upgradeQ/OBS-Studio-Cursor-skin#11]
1.
C:\Program Files\obs-studio\OBS-Studio-Cursor-skin-2.3.0>mouse_skin_obs.py
Traceback (most recent call last):
  File "C:\Program Files\obs-studio\OBS-Studio-Cursor-skin-2.3.0\mouse_skin_obs.py", line 1, in <module>
    import obspython as S  # studio
ModuleNotFoundError: No module named 'obspython'

2.
C:\Program Files\obs-studio\OBS-Studio-Cursor-skin-2.3.0>python -m pip install obspython
Looking in indexes: https://pypi.org/simple, https://pypi.ngc.nvidia.com
ERROR: Could not find a version that satisfies the requirement obspython (from versions: none)
ERROR: No matching distribution found for obspython

C:\Program Files\obs-studio\OBS-Studio-Cursor-skin-2.3.0>py -0
Installed Pythons found by py Launcher for Windows
 -3.10-64 *

**Comment by upgradeQ** [comment]
You need to load this script into OBS Studio, it will not work as a standalone program - see first part of [this](https://obsproject.com/kb/scripting-guide) tutorial.

**Comment by AngelTs** [comment]
There is no Cursor option in Sources window after load the script mouse_skin_obs.py in Tools-Scripts

**Comment by upgradeQ** [comment]
"Cursor" is just a name for a source, e.g media source, image source. You have to add it yourself and select that source.

**Comment by AngelTs** [comment]
unbelievable ...
