### ISSUE TITLE
Mouse pointer offset.

### ISSUE THREAD

**Issue by mayank1513** [upgradeQ/OBS-Studio-Cursor-skin#2]
Nice script but some issues needs to be resolved before it can be used. 

The image and cursor have large offset. I am using two monitors/display. I am capturing my second display. But image follows the mouse pointer only on primary display and that too with large offset.

**Comment by upgradeQ** [comment]
Offset happens when you resize the source which is used for cursor. This is fixed in [`update_crop`](https://github.com/upgradeQ/OBS-Studio-Cursor-skin/blob/f32d168def969d6064518816e73a385c34afd733/mouse_skin_obs.py#L35-L60) which is used for zoom and highlight (if not resized).  

Multiple monitors setup is not supported.

**Comment by upgradeQ** [comment]
@mayank1513 resizing now works.
-  https://github.com/upgradeQ/OBS-Studio-Cursor-skin/commit/ad8ca1face962ac5ffa5294f1cda709bd7012abc 

Let me know if bug is persist.

**Comment by Karmalakas** [comment]
_Update crop_ doesn't change anything. I have cropped area and highlight image follows cursor as if recorded area wasn't cropped. It matches cursor when in one corner, but moving away from the corner increases the offset. What am I missing?

**Comment by upgradeQ** [comment]
@Karmalakas  what is your use case? If you are trying to create zoom, might as well try using this script https://github.com/tryptech/obs-zoom-and-follow  . _Update crop_ checkbox is used  for highlighting e.g: invert color, change gamma via color correction filter. It can be used as [zoom](https://github.com/upgradeQ/OBS-Studio-Cursor-skin#crop-auto-update) but there is better solution for that by zoom and follow script. 
If possible, can you create gif / video with what are you trying to do?

**Comment by Karmalakas** [comment]
[Here](https://youtu.be/olMYzFZbpaA) you go. I hope this clarifies what I mean :) All I want, is just for the image to follow cursor

**Comment by upgradeQ** [comment]
Do your monitor resolution match base canvas resolution?

**Comment by Karmalakas** [comment]
Looks like it does
![image](https://user-images.githubusercontent.com/3602819/102001157-596f7f00-3cf7-11eb-98ca-e630fc442d60.png)

**Comment by upgradeQ** [comment]
There can't be any offset issue if you'll set base canvas resolution to your monitor resolution. Try adding a desktop capture again( so it will be updated). Also, did you resize your cursor (some scene item) ?

**Comment by Karmalakas** [comment]
It works fine until I add crop filter
![image](https://user-images.githubusercontent.com/3602819/102008154-251bb300-3d37-11eb-8015-ea178cfcd789.png)

**Comment by Karmalakas** [comment]
Also noticed, if crop ratio doesn't match output ratio and I move desktop source to the left, cursor image completely ignores where my desktop ends and goes beyond the monitor frame (don't even know how to explain). It seems all cursor script cares about, is full display resolution and where cursor is on display and calculates where it should be on the output

https://youtu.be/D5sT1DUaMu0

**Comment by upgradeQ** [comment]
> It seems all cursor script cares about, is full display resolution and where cursor is on display and calculates where it should be on the output

Exactly, here is  the logic behind that https://github.com/upgradeQ/OBS-Studio-Cursor-skin/blob/e02d2bd674cb3d9a7ded2cd3732a1a21968ad54c/mouse_skin_obs.py#L32-L42
You might also try different approach with scene item transform, hold <kbd>alt</kbd> and adjust crop region via dragging borders.

**Comment by Karmalakas** [comment]
But then in output video it leaves all this black area :(
I guess I'll just have to crop video after recording it

Anyway, thank you for this nice script :)

**Comment by upgradeQ** [comment]
Okay, I am closing it then.
