### ISSUE TITLE
No module named 'pynput'

### ISSUE THREAD

**Issue by baozugong** [upgradeQ/OBS-Studio-Cursor-skin#3]
It throw the exception"  No module named 'pynput'  ", even though I've installed this module.

[mouse_skin_obs.py] Traceback (most recent call last):
[mouse_skin_obs.py]   File "D:/Program Files/obs-studio/data/obs-plugins/frontend-tools/scripts\mouse_skin_obs.py", line 2, in <module>
[mouse_skin_obs.py]     from pynput.mouse import Controller  # python -m pip install pynput
[mouse_skin_obs.py] ModuleNotFoundError: No module named 'pynput'

**Comment by upgradeQ** [comment]
@baozugong where did you install it? If you did set path to python3.6 (since you on windows) , your python3.6 needs to have it, maybe you've installed it to your global python. Try using this:
- Open folder with python3.6 there is should be `python.exe` , in explorer click on current path bar, type `cmd` , press <kbd>enter</kbd> , then `python -m pip install pynput`

**Comment by Swizzler121** [comment]
Didn't resolve the issue. 

Installed specified version indicated in #1, installed pynput, still get same error. Console output:

`[mouse_skin_obs.py] Traceback (most recent call last):`
`[mouse_skin_obs.py]   File "C:/Program Files/obs-studio/data/obs-plugins/frontend-tools/scripts\mouse_skin_obs.py", line 2, in <module>`
`[mouse_skin_obs.py]     from pynput.mouse import Controller  # python -m pip install pynput`
`[mouse_skin_obs.py] ModuleNotFoundError: No module named 'pynput'`

output when running `python -m pip install pynput`

`Requirement already satisfied: pynput in c:\{{appdatadirectory}}\local\programs\python\python36\lib\site-packages (1.7.1)`
`Requirement already satisfied: six in c:\{{appdatadirectory}}\local\programs\python\python36\lib\site-packages (from pynput) (1.15.0)`

set python install directory:
`
C:/{{appdatadirectory}}/Local/Programs/Python/Python36`

**Comment by upgradeQ** [comment]
Hello @Swizzler121 , in a path with python3.6 **which OBS Studio uses**, if you open `python.exe`  then run this code  `import pynput; dir(pynput)` is it still raises `ModuleNotFoundError` ?

**Comment by Swizzler121** [comment]
That fixed it! thank you very much.

**Comment by yiddytlq** [comment]
hi @upgradeQ I am having the exact same issue as the OP & when I run `import pynput; dir(pynput)` i get 
```
C:\Program Files\Python36>python
Python 3.6.8 (tags/v3.6.8:3c6b436a57, Dec 24 2018, 00:16:47) [MSC v.1916 64 bit (AMD64)] on win32 Type "help", "copyright", "credits" or "license" for more information.
>>> import pynput; dir(pynput)
['__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '_logger', '_util', 'keyboard', 'mouse']
```

However when I try to run the script I still get the error 
```
[mouse_skin_obs.py] Traceback (most recent call last):
[mouse_skin_obs.py]   File "C:/Users/Yiddy/Downloads/OBS-Studio-Cursor-skin-master\mouse_skin_obs.py", line 6, in <module>
[mouse_skin_obs.py]     from pynput.mouse import Controller  # python -m pip install pynput
[mouse_skin_obs.py] ModuleNotFoundError: No module named 'pynput'
```

When running `python -m pip install pynput` I get 
```
Requirement already satisfied: pynput in c:\users\yiddy\appdata\roaming\python\python36\site-packages (1.7.6)
Requirement already satisfied: six in c:\users\yiddy\appdata\roaming\python\python36\site-packages (from pynput) (1.16.0)
```

**Comment by upgradeQ** [comment]
Hello @yiddytlq , you should try moving pynput folder in directory where script resides.
```python
import pathlib, sys
print(1,pathlib.Path(__file__).parent.resolve())
print(2,sys.executable)
```
1 - path where you should move `pynput` package
2 - path which must have `pynput` installed

**Comment by yiddytlq** [comment]
@upgradeQ thanks, I noticed your comment now however I have already found a similar workaround.

I ended up moving it to the folder where obspython is. I then ran into the same issue for some other python modules (I think six & some others) & copied those to the same folder.
