### ISSUE TITLE
Cursor on top of image

### ISSUE THREAD

**Issue by qo4on** [upgradeQ/OBS-Studio-Cursor-skin#7]
Hi!
Is there a way to capture a cursor on top of an image? The added image colors the cursor, I'd like to avoid this.

![image](https://user-images.githubusercontent.com/35609308/133887835-68b1c6e0-54b2-43a7-afba-8310e2d01b95.png)

**Comment by upgradeQ** [comment]
Currently - no, a workaround might be creating a group source where you have an image with cursor and highlight part with yours defined order.

**Comment by qo4on** [comment]
But the cursor changes when you click on a text field, for example, so this change will not be visible, right?

**Comment by upgradeQ** [comment]
No, you need to add static image of a cursor (or any source ) then highlight source , compose it in a group source , and select that group source in dropdown menu of a script. Capture cursor must be unchecked. 
Cursor states and location are not routed to `obspython` nor `obslua`.

**Comment by qo4on** [comment]
One more thing. Do you know why do images or videos with transparency show incorrect colors? For example, the yellow circle with 50% alpha (rgb 255, 255, 0) becomes brown instead of (rgb 255, 255, 127).
![image](https://user-images.githubusercontent.com/35609308/146298122-7ff0dcea-c12b-448d-a857-c0909d5b1885.png)

**Comment by upgradeQ** [comment]
As I see on my screenshot, it is hard to notice a difference on a light background.


![image](https://user-images.githubusercontent.com/18361586/146377291-6d4147ec-ed2d-4823-8ab9-5ad9356aaa47.png)


But you might also ask someone in community experienced with color correctness and OBS Studio graphic subsystem.

**Comment by qo4on** [comment]
Both circles on my screenshot are on the same white background and they must be the same color. I believe your plugin does alpha multiplication on an already **premultiplied** alpha image. This causes all semi-transparent colors to be wrong.
https://stackoverflow.com/questions/10768836/how-does-alpha-blending-work-mathematically-pixel-by-pixel

**Comment by upgradeQ** [comment]
There must be something wrong with an image, I've checked code there is only scale operations to center a scene item. Maybe try non-transparent image and use Color Correction filter on that source? I've created image presets with transparency as an example, in the next version there will be updated README regarding that use-case and included assets.

**Comment by qo4on** [comment]
There is nothing can be wrong with an image. A transparent image is a simple 4-dimentional array of integer values (r,g,b,a) in a range [0, 255]. You are getting correct colors only when `alpha = 0` and `alpha = 255`.

Create a clear yellow circle (rgb 255, 255, 0) in any program. Then set its opacity to 50%. Then put it on a transparent background, save and use in OBS on a white (rgb 255, 255, 255) background. At the end compare the result with your initial 50% opacity image placed over the same white bg. You will get different colors.
